---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local
  
  vars:
    image_name: my-country-service
    image_tag: v1
    dockerfile_path: '.'
    docker_registry_username: "oumayma511"
    docker_registry_password: "dckr_pat_2ff-HkUO5yLPa_kiiD9t-v9IzOY"
  
  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes
    
    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}:{{ image_tag }}"
        source: build
        state: present
    
    - name: Push the Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}:{{ image_tag }}"
        push: yes
        source: local
    
    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: deployment.yaml
        kubeconfig: config
    
    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config
